// Auto-generated by watermark processor — do not edit directly
export const PRINT_SIZES = [
  {
    "label": "8×10",
    "price": 125
  },
  {
    "label": "11×14",
    "price": 185
  },
  {
    "label": "16×20",
    "price": 280
  },
  {
    "label": "20×30",
    "price": 575
  },
  {
    "label": "24×36",
    "price": 650
  }
] as const

export const PRINT_MEDIUMS = ['Metal', 'Canvas'] as const
export type PrintMedium = typeof PRINT_MEDIUMS[number]

export interface Photo {
  id: string
  filename: string
  title: string
  description: string
  category: string
}

export const CATEGORIES: Record<string, { label: string; description: string }> = {
  nature: {
    label: 'Nature',
    description: 'Landscapes, wildlife, and the natural world — from the Mojave Desert to the Tuscan hills.',
  },
  'san-francisco': {
    label: 'San Francisco Bay',
    description: 'The bay, the bridges, and the light that makes this place unlike anywhere else.',
  },
}

export const photos: Record<string, Photo[]> = {
  "nature": [
    {
      "id": "backlit-sentinel-cap-rock-under-the-stars",
      "filename": "backlit-sentinel-cap-rock-under-the-stars.jpg",
      "title": "Backlit Sentinel — Cap Rock Under the Stars",
      "description": "The famous Cap Rock formation at Joshua Tree National Park silhouetted against a brilliant Milky Way. Shot during a rare clear desert night with minimal light pollution, the stars form a river of light above the ancient granite.",
      "category": "nature"
    },
    {
      "id": "blue-morpho-s-secret-eyes",
      "filename": "blue-morpho-s-secret-eyes.jpg",
      "title": "Blue Morpho's Secret Eyes",
      "description": "A stunning close-up revealing the intricate eyespot patterns on a Blue Morpho butterfly's wing undersides. Captured in natural light, these hidden eyes serve as the butterfly's first line of defense against predators.",
      "category": "nature"
    },
    {
      "id": "bufflehead-ballet",
      "filename": "bufflehead-ballet.jpg",
      "title": "Bufflehead Ballet",
      "description": "Two Bufflehead ducks mid-courtship on glassy water, their iridescent plumage catching the morning light in perfect symmetry. These smallest of North American diving ducks are rarely this still.",
      "category": "nature"
    },
    {
      "id": "crimson-patch-longwing-on-lantana",
      "filename": "crimson-patch-longwing-on-lantana.jpg",
      "title": "Crimson Patch Longwing on Lantana",
      "description": "A vivid Crimson Patch Longwing butterfly feeds on a cluster of Lantana blooms, its scarlet and black wings spread wide. Lantana's dense flower clusters make it a favorite nectar source for longwing butterflies throughout their range.",
      "category": "nature"
    },
    {
      "id": "dahlia-symphony",
      "filename": "dahlia-symphony.jpg",
      "title": "Dahlia Symphony",
      "description": "A garden of dahlias in full late-summer bloom, their layered petals composing a symphony of color from deep crimson to pale gold. Dahlias are among the few flowers that grow more complex the longer they bloom.",
      "category": "nature"
    },
    {
      "id": "delicate-arch-at-dawn",
      "filename": "delicate-arch-at-dawn.jpg",
      "title": "Delicate Arch at Dawn",
      "description": "Utah's most iconic natural arch photographed in the first light of dawn, when the Entrada sandstone glows warm amber against a pale sky. The 52-foot arch took millions of years of erosion to carve.",
      "category": "nature"
    },
    {
      "id": "el-truko",
      "filename": "el-truko.jpg",
      "title": "El Truko",
      "description": "A weathered vintage truck stands as an accidental monument to the American West, its rust and sun-bleached surfaces telling decades of desert stories. Found near an abandoned homestead in the California high desert.",
      "category": "nature"
    },
    {
      "id": "ghost-town-coupe",
      "filename": "ghost-town-coupe.jpg",
      "title": "Ghost Town Coupe",
      "description": "A vintage automobile, frozen in time, rests in an abandoned ghost town. The passage of decades has turned it into unintentional sculpture — rust, dust, and desert light conspiring to make something beautiful.",
      "category": "nature"
    },
    {
      "id": "gondolas-of-venice",
      "filename": "gondolas-of-venice.jpg",
      "title": "Gondolas of Venice",
      "description": "Classic Venetian gondolas bob gently on a quiet canal before the morning tourist crowds arrive, their ornate ferro prows reflected in still water. This is Venice as it has looked for centuries.",
      "category": "nature"
    },
    {
      "id": "jewels-of-pride-of-madeira",
      "filename": "jewels-of-pride-of-madeira.jpg",
      "title": "Jewels of Pride of Madeira",
      "description": "The vibrant jewel-toned flowers of the Pride of Madeira plant — each tiny bloom a gem in purple and violet — catch the morning light along the California coast where this Mediterranean plant has naturalized.",
      "category": "nature"
    },
    {
      "id": "ladybug-on-winter-branch",
      "filename": "ladybug-on-winter-branch.jpg",
      "title": "Ladybug on Winter Branch",
      "description": "A solitary ladybug makes her way along a bare winter branch, a small burst of crimson against a pale landscape. Ladybugs overwinter in clusters but occasionally emerge alone on warmer days.",
      "category": "nature"
    },
    {
      "id": "lotus-serenity",
      "filename": "lotus-serenity.jpg",
      "title": "Lotus Serenity",
      "description": "A single lotus blossom rises from still water, its pink petals unfurling in perfect peace. The lotus has been a symbol of purity and enlightenment for thousands of years — its roots in mud, its flower in light.",
      "category": "nature"
    },
    {
      "id": "milky-way-over-hidden-valley",
      "filename": "milky-way-over-hidden-valley.jpg",
      "title": "Milky Way Over Hidden Valley",
      "description": "The core of our galaxy arches over Joshua Tree's Hidden Valley, a river of stars flowing between the iconic Jumbo Rocks formations. The Mojave Desert's low humidity and sparse population make it one of California's best stargazing destinations.",
      "category": "nature"
    },
    {
      "id": "milky-way-over-joshua-tree",
      "filename": "milky-way-over-joshua-tree.jpg",
      "title": "Milky Way Over Joshua Tree",
      "description": "A lone Joshua Tree — found only in the Mojave Desert — reaches upward toward the full sweep of the Milky Way in this long-exposure night photograph. These trees can live for hundreds of years.",
      "category": "nature"
    },
    {
      "id": "mists-of-tuscany",
      "filename": "mists-of-tuscany.jpg",
      "title": "Mists of Tuscany",
      "description": "Rolling Tuscan hillsides wrapped in morning mist, with a lone cypress-lined road disappearing into soft golden haze. This landscape has been painted, photographed, and written about for centuries — and still surprises.",
      "category": "nature"
    },
    {
      "id": "oakland-in-a-sea-of-clouds",
      "filename": "oakland-in-a-sea-of-clouds.jpg",
      "title": "Oakland in a Sea of Clouds",
      "description": "Oakland's downtown skyline floats above a dense marine layer that fills the bay, creating the striking illusion of a city built on clouds. This view from the hills requires patience — the fog must be deep enough to cover the bay but thin enough to clear the buildings.",
      "category": "nature"
    },
    {
      "id": "paper-kite-in-bloom",
      "filename": "paper-kite-in-bloom.jpg",
      "title": "Paper Kite in Bloom",
      "description": "A Paper Kite butterfly — its wings like translucent stained glass in white and black — rests on a tropical flower in full bloom. Found throughout Southeast Asia, the Paper Kite is one of the largest and most graceful of the brush-footed butterflies.",
      "category": "nature"
    },
    {
      "id": "path-beneath-the-annular-sun",
      "filename": "path-beneath-the-annular-sun.jpg",
      "title": "Path Beneath the Annular Sun",
      "description": "A remarkable annular solar eclipse captured at its peak, the ring of fire hovering above a winding desert trail. During an annular eclipse, the moon is too far from Earth to fully cover the sun, leaving a glowing ring.",
      "category": "nature"
    },
    {
      "id": "prairie-giants",
      "filename": "prairie-giants.jpg",
      "title": "Prairie Giants",
      "description": "Towering wind turbines stand sentinel on the California prairie, their blades turning slowly against a wide, open sky. The same winds that once drove the great cattle drives now power tens of thousands of homes.",
      "category": "nature"
    },
    {
      "id": "royal-display",
      "filename": "royal-display.jpg",
      "title": "Royal Display",
      "description": "A male bird of paradise in full courtship display, his plumage an explosion of iridescent color arranged to maximize impact. These birds spend years perfecting their displays before attracting a mate.",
      "category": "nature"
    },
    {
      "id": "sentinel-of-the-still-waters",
      "filename": "sentinel-of-the-still-waters.jpg",
      "title": "Sentinel of the Still Waters",
      "description": "A great blue heron stands motionless at the edge of a glassy pond, patient and perfectly still in the early morning quiet. Great blue herons can stand without moving for thirty minutes or more while waiting for fish to come within reach.",
      "category": "nature"
    },
    {
      "id": "spring-fields-of-san-luis-obispo",
      "filename": "spring-fields-of-san-luis-obispo.jpg",
      "title": "Spring Fields of San Luis Obispo",
      "description": "Rolling hills of San Luis Obispo County carpeted in spring wildflowers after a wet winter, the landscape rippling with lupine, poppies, and mustard. The Central Coast's wildflower displays are among California's most spectacular.",
      "category": "nature"
    },
    {
      "id": "storm-light-over-avila-pier",
      "filename": "storm-light-over-avila-pier.jpg",
      "title": "Storm Light Over Avila Pier",
      "description": "Dramatic storm light breaks through the clouds above Avila Beach Pier, casting a golden spotlight on the Pacific and painting the century-old wooden pier in warm amber. These windows of light last only seconds.",
      "category": "nature"
    },
    {
      "id": "storm-watch-at-walton-lighthouse",
      "filename": "storm-watch-at-walton-lighthouse.jpg",
      "title": "Storm Watch at Walton Lighthouse",
      "description": "The Mark Abbott Memorial Lighthouse — known locally as the Walton Lighthouse — stands firm as a winter storm churns the surf around it, waves breaking white against the concrete tower at the Santa Cruz harbor mouth.",
      "category": "nature"
    },
    {
      "id": "surrey-bikes-of-pismo-beach",
      "filename": "surrey-bikes-of-pismo-beach.jpg",
      "title": "Surrey Bikes of Pismo Beach",
      "description": "Colorful surrey bikes line the Pismo Beach boardwalk on a bright afternoon, their fringed canopies catching the sea breeze. Pismo has offered these four-wheeled pedal carriages for decades — one of the California coast's enduring simple pleasures.",
      "category": "nature"
    },
    {
      "id": "sweat-bee-on-russian-sage",
      "filename": "sweat-bee-on-russian-sage.jpg",
      "title": "Sweat Bee on Russian Sage",
      "description": "A tiny metallic sweat bee works the lavender-blue spires of Russian Sage, her compact body dusted with pollen. Sweat bees are among our most important pollinators and among our most beautiful — often overlooked because of their small size.",
      "category": "nature"
    },
    {
      "id": "the-lone-cypress",
      "filename": "the-lone-cypress.jpg",
      "title": "The Lone Cypress",
      "description": "The famous Lone Cypress at Pebble Beach — perhaps California's most photographed tree — clings to its granite perch above Carmel Bay. Estimated to be over 250 years old, it has been a protected landmark since 1990.",
      "category": "nature"
    },
    {
      "id": "twilight-at-manhattan-beach-pier",
      "filename": "twilight-at-manhattan-beach-pier.jpg",
      "title": "Twilight at Manhattan Beach Pier",
      "description": "The Manhattan Beach Pier extends into a twilight sky ablaze with color, the Pacific glowing purple and rose below. The pier, rebuilt after a 1913 storm, has been a gathering place on the South Bay for over a century.",
      "category": "nature"
    },
    {
      "id": "twisted-survivor-of-the-canyon",
      "filename": "twisted-survivor-of-the-canyon.jpg",
      "title": "Twisted Survivor of the Canyon",
      "description": "An ancient bristlecone pine — possibly thousands of years old — gnarled and sculpted by centuries of high-altitude wind and weather, persists where almost nothing else can. These trees survive precisely because they grow so slowly.",
      "category": "nature"
    },
    {
      "id": "white-lined-sphinx-among-sweet-williams",
      "filename": "white-lined-sphinx-among-sweet-williams.jpg",
      "title": "White-Lined Sphinx Among Sweet Williams",
      "description": "A fine art photograph by Imad. Printed on archival paper with pigment inks for lasting color.",
      "category": "nature"
    },
    {
      "id": "zebra-longwing-on-lantana",
      "filename": "zebra-longwing-on-lantana.jpg",
      "title": "Zebra Longwing on Lantana",
      "description": "A bold Zebra Longwing butterfly — Florida's official state butterfly — rests on bright Lantana blossoms in dappled garden light. Unlike most butterflies, Zebra Longwings can digest pollen, giving them a lifespan of several months rather than weeks.",
      "category": "nature"
    }
  ],
  "san-francisco": [
    {
      "id": "bay-of-gold",
      "filename": "bay-of-gold.jpg",
      "title": "Bay of Gold",
      "description": "San Francisco Bay catches the last golden light of late afternoon, the water transformed into hammered gold under a blazing sky. From this angle, the bay becomes less a body of water than a mirror for the sun.",
      "category": "san-francisco"
    },
    {
      "id": "blue-angels-over-the-golden-gate",
      "filename": "blue-angels-over-the-golden-gate.jpg",
      "title": "Blue Angels Over the Golden Gate",
      "description": "The U.S. Navy's Blue Angels precision flight team roars over the Golden Gate Bridge during Fleet Week, the F/A-18 Hornets trailing vapor against an October sky. Fleet Week has drawn this kind of spectacle to the bay since 1981.",
      "category": "san-francisco"
    },
    {
      "id": "bridging-two-eras",
      "filename": "bridging-two-eras.jpg",
      "title": "Bridging Two Eras",
      "description": "The Bay Bridge's new eastern span alongside its predecessor, a photograph about time, engineering, and the bay's constant presence beneath both. The old span was demolished after the new one opened in 2013.",
      "category": "san-francisco"
    },
    {
      "id": "dsc03766-101217-fire-suns",
      "filename": "dsc03766-101217-fire-suns.jpg",
      "title": "Fire Suns",
      "description": "During the devastating 2017 North Bay fires, smoke turned the Bay Area sun blood-red for days — an eerie, apocalyptic light unlike anything most residents had ever seen. This image was made in the middle of the afternoon.",
      "category": "san-francisco"
    },
    {
      "id": "fireworks-over-the-bay",
      "filename": "fireworks-over-the-bay.jpg",
      "title": "Fireworks Over the Bay",
      "description": "Fourth of July fireworks burst over San Francisco Bay in a long-exposure reflection of light and color, the display mirrored in the dark water below the Bay Bridge.",
      "category": "san-francisco"
    },
    {
      "id": "gateway-to-the-pacific",
      "filename": "gateway-to-the-pacific.jpg",
      "title": "Gateway to the Pacific",
      "description": "The Golden Gate Bridge photographed from the Marin Headlands, framing the bay and the city skyline beyond. Completed in 1937, it was for decades the longest suspension bridge in the world.",
      "category": "san-francisco"
    },
    {
      "id": "golden-burst-over-the-bay",
      "filename": "golden-burst-over-the-bay.jpg",
      "title": "Golden Burst Over the Bay",
      "description": "A spectacular sunburst erupts through a break in the storm clouds over San Francisco Bay, flooding the choppy water with light in a shaft that lasted only a few minutes.",
      "category": "san-francisco"
    },
    {
      "id": "golden-gate-in-the-mist",
      "filename": "golden-gate-in-the-mist.jpg",
      "title": "Golden Gate in the Mist",
      "description": "The Golden Gate Bridge partly veiled in the famous San Francisco fog, the south tower visible while the north disappears into the marine layer. The bridge was specifically painted international orange to remain visible in this fog.",
      "category": "san-francisco"
    },
    {
      "id": "harvest-moon-over-the-bay",
      "filename": "harvest-moon-over-the-bay.jpg",
      "title": "Harvest Moon Over the Bay",
      "description": "A full harvest moon rises enormous and orange above the San Francisco Bay, its reflection stretching across the water between the Bay Bridge's lights. The harvest moon's low trajectory through the atmosphere makes it appear far larger than it is.",
      "category": "san-francisco"
    },
    {
      "id": "moonrise-between-two-bridges",
      "filename": "moonrise-between-two-bridges.jpg",
      "title": "Moonrise Between Two Bridges",
      "description": "The moon rises perfectly framed between the Bay Bridge and the Golden Gate in this carefully timed photograph. Predicting this alignment requires calculating the moon's exact position weeks in advance.",
      "category": "san-francisco"
    },
    {
      "id": "the-bay-beneath-the-clouds",
      "filename": "the-bay-beneath-the-clouds.jpg",
      "title": "The Bay Beneath the Clouds",
      "description": "A wide view of the entire bay system from elevation above the marine layer, the bridges tracing silver lines across the blue water, the city a cluster of white on the peninsula tip.",
      "category": "san-francisco"
    }
  ]
}
