// Auto-generated by scripts/watermark/process.js
// Run node process.js to populate with real photo data

export const PRINT_SIZES = [
  { label: '8×10',   price: 125 },
  { label: '11×14',  price: 185 },
  { label: '16×20',  price: 280 },
  { label: '20×30',  price: 575 },
  { label: '24×36',  price: 650 },
] as const

export const PRINT_MEDIUMS = ['Metal', 'Canvas'] as const
export type PrintMedium = typeof PRINT_MEDIUMS[number]

export interface Photo {
  id: string
  filename: string
  title: string
  description: string
  category: string
}

export const CATEGORIES: Record<string, { label: string; description: string }> = {
  nature: {
    label: 'Nature',
    description: 'Landscapes, wildlife, and the natural world — from the Mojave Desert to the Tuscan hills.',
  },
  'san-francisco': {
    label: 'San Francisco Bay',
    description: 'The bay, the bridges, and the light that makes this place unlike anywhere else.',
  },
}

export const photos: Record<string, Photo[]> = {
  nature: [],
  'san-francisco': [],
}
